In [2]:
# Generate a np array of (a) vector of lenght 50 (b) two dimension of shape 5x4. Both uniformly distributed between 0 and 1
# Split the two dimension array in 1 above into three arrays taking the first two rows, follow by the next two rows and put the remaining row in another variable
# Split the vector into in 1 above three arrays by taking the first 15, follow by the next 20 and the remaining into another variable.
# Create a 4x5 array: (a). Using manual method (b). Using randomly generated value between 0 and 1 (c). Using array of ones

In [3]:
import numpy as np
vector = np.random.random(50)
vector

array([0.77257681, 0.30717138, 0.74321404, 0.51378628, 0.2704007 ,
       0.29258121, 0.34244674, 0.0103403 , 0.18815921, 0.60942734,
       0.82362651, 0.99546185, 0.07625555, 0.74009076, 0.27839256,
       0.2647458 , 0.54717379, 0.96124667, 0.60187314, 0.31059979,
       0.41851988, 0.81439615, 0.92188329, 0.02774975, 0.66739792,
       0.64302647, 0.86971284, 0.106705  , 0.74525932, 0.53636626,
       0.26207121, 0.67889179, 0.74713553, 0.20235079, 0.33193948,
       0.46570948, 0.68521971, 0.9711043 , 0.18013798, 0.33997622,
       0.78136364, 0.3820475 , 0.29021532, 0.66858549, 0.67385885,
       0.93252571, 0.94394304, 0.41088519, 0.73715299, 0.74276184])

In [4]:
vector_1 = np.random.random((5,4))
vector_1

array([[0.04351852, 0.90481682, 0.08926273, 0.95721372],
       [0.92178314, 0.96800281, 0.30614453, 0.45240293],
       [0.86085438, 0.7919818 , 0.15006093, 0.84474472],
       [0.08389702, 0.6477365 , 0.53735086, 0.86878982],
       [0.57704331, 0.71705413, 0.38156197, 0.17246893]])

In [14]:
vector_2, vector_3, vector_4 = np.vsplit(vector_1, [2,4])
vector_2, vector_3, vector_4
# Alternatively: 
# vector_new = np.array_split(vector_1, 3, axis = 0)
# vector_new

(array([[0.04351852, 0.90481682, 0.08926273, 0.95721372],
        [0.92178314, 0.96800281, 0.30614453, 0.45240293]]),
 array([[0.86085438, 0.7919818 , 0.15006093, 0.84474472],
        [0.08389702, 0.6477365 , 0.53735086, 0.86878982]]),
 array([[0.57704331, 0.71705413, 0.38156197, 0.17246893]]))

In [16]:
vector_5, vector_6, vector_7 = np.split(vector, (15, 35))
vector_5, vector_6, vector_7

(array([0.77257681, 0.30717138, 0.74321404, 0.51378628, 0.2704007 ,
        0.29258121, 0.34244674, 0.0103403 , 0.18815921, 0.60942734,
        0.82362651, 0.99546185, 0.07625555, 0.74009076, 0.27839256]),
 array([0.2647458 , 0.54717379, 0.96124667, 0.60187314, 0.31059979,
        0.41851988, 0.81439615, 0.92188329, 0.02774975, 0.66739792,
        0.64302647, 0.86971284, 0.106705  , 0.74525932, 0.53636626,
        0.26207121, 0.67889179, 0.74713553, 0.20235079, 0.33193948]),
 array([0.46570948, 0.68521971, 0.9711043 , 0.18013798, 0.33997622,
        0.78136364, 0.3820475 , 0.29021532, 0.66858549, 0.67385885,
        0.93252571, 0.94394304, 0.41088519, 0.73715299, 0.74276184]))

In [7]:
val_2 = np.arange(1,21)
val_2 = val_2.reshape(4,5)
val_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
var_4 = np.random.random(20)
var_4 = var_4.reshape(4,5)
var_4

array([[0.50860237, 0.84925456, 0.87994198, 0.49469608, 0.44490327],
       [0.76359116, 0.62725379, 0.76034544, 0.41371828, 0.46057733],
       [0.45249673, 0.57524496, 0.07905636, 0.08316806, 0.24690646],
       [0.77863666, 0.92841719, 0.38122152, 0.16368375, 0.30575693]])

In [9]:
var_5 = np.ones(20)
var_5 = var_5.reshape(4,5)
var_5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])