In [ ]:
use us_births data to compute the following using np:
    extract the year, gender and births column from the data
    compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean and median
    compute the maximum births and minimum births
    indicate the gender with minimum birth and maximum birth
    indicate the year with minimum birth and maximum birth

In [46]:
import numpy as np
import pandas as pd

us_birth_record = pd.read_csv("C:\\Datasets\\us_births.csv")
us_birth_record

year  month  day gender  births
0      1969      1  1.0      F    4046
1      1969      1  1.0      M    4440
2      1969      1  2.0      F    4454
3      1969      1  2.0      M    4548
4      1969      1  3.0      F    4548
...     ...    ...  ...    ...     ...
15542  2008     10  NaN      M  183219
15543  2008     11  NaN      F  158939
15544  2008     11  NaN      M  165468
15545  2008     12  NaN      F  173215
15546  2008     12  NaN      M  181235

[15547 rows x 5 columns]

In [18]:
us_birth_record.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15547 entries, 0 to 15546
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   year    15547 non-null  int64  
 1   month   15547 non-null  int64  
 2   day     15067 non-null  float64
 3   gender  15547 non-null  object 
 4   births  15547 non-null  int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 607.4+ KB


In [47]:
us_years = np.array(us_birth_record['year'])
us_gender = np.array(us_birth_record['gender'])
us_births = np.array(us_birth_record['births'])

print('US population year of birth\n', us_years, '\n')
print('US population gender\n', us_gender, '\n')
print('US population births\n', us_years)

US population year of birth
 [1969 1969 1969 ... 2008 2008 2008] 

US population gender
 ['F' 'M' 'F' ... 'M' 'F' 'M'] 

US population births
 [1969 1969 1969 ... 2008 2008 2008]


In [37]:
# Sum of total birth for females 
female_births = np.array(us_birth_record['births'][us_birth_record['gender'] == 'F'])
female_births
mean_val = np.mean(female_births)
median_val = np.median(female_births)
sum_val = female_births.sum()
print('Female birth record is: \n', female_births, '\n')
print('Sum of record is: ', sum_val, '\n')
print('Mean value: ', mean_val, '\n')
print('Median value: ', median_val, '\n')
print('Maximum birth: ', female_births.max(), '\n')
print('Minimum birth: ', female_births.min(), '\n')

Female birth record is: 
 [  4046   4454   4548 ... 175314 158939 173215] 

Sum of record is:  74035823 

Mean value:  9521.067772633745 

Median value:  4688.5 

Maximum birth:  191495 

Minimu birth:  1 



In [39]:
# sum of birth for males
male_births = np.array(us_birth_record['births'][us_birth_record['gender'] == 'M'])
male_births
mean_val = np.mean(male_births)
median_val = np.median(male_births)
sum_val = male_births.sum()
print('Male birth record is: \n', male_births, '\n')
print('Sum of record is: ', sum_val, '\n')
print('Mean value: ', mean_val, '\n')
print('Median value: ', median_val, '\n')
print('Maximum birth: ', male_births.max(), '\n')
print('Minimum birth: ', male_births.min(), '\n')


Male birth record is: 
 [  4440   4548   4994 ... 183219 165468 181235] 

Sum of record is:  77738555 

Mean value:  10003.674559258783 

Median value:  4938.0 

Maximum birth:  199622 

Minimum birth:  1 



In [41]:
# Maximum birth 
print('Maximum birth: ', us_birth_record.max(),'\n') 
print('Minimum birth: ', us_birth_record.min(), '\n')

Maximum birth:  year        2008
month         12
day         99.0
gender         M
births    199622
dtype: object 

Minimum birth:  year      1969
month        1
day        1.0
gender       F
births       1
dtype: object 



In [48]:
max_birth = us_births.max()
min_birth = us_births.min()
gender_with_maxbirth = us_gender
total_birth = np.sum(us_birth_record['births'])
print('The maximum birth: ', max_birth, '\n')
print('The minimum birth: ', min_birth, '\n')
print('Sum of Total birth: ', total_birth)

The maximum birth:  199622 

The minimum birth:  1 

Sum of Total birth:  151774378


In [50]:
x = np.arange(1,13).reshape(1,12)
y = np.arange(1,13).reshape(12,1)
x * y

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])