QUESTION 1

In [9]:
import pandas as pd
import numpy as np
data_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

custom_index = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

custom_series = pd.Series(data_list, index=custom_index)
custom_series

A     10
B     20
C     30
D     40
E     50
F     60
G     70
H     80
I     90
J    100
dtype: int64

QUESTION 2

In [6]:
data_dict = {'A': 10, 'B': 20, 'C': 30, 'D': 40, 'E': 50, 'F': 60, 'G': 70, 'H': 80, 'I': 90, 'J': 100}
dict_series = pd.Series(data_dict)
dict_series

A     10
B     20
C     30
D     40
E     50
F     60
G     70
H     80
I     90
J    100
dtype: int64

QUESTION 3

In [8]:
custom_df = pd.DataFrame(custom_series, columns=['Values'])
custom_df

Values
A      10
B      20
C      30
D      40
E      50
F      60
G      70
H      80
I      90
J     100

QUESTION 4

In [11]:
column_names = ['Column1', 'Column2', 'Column3', 'Column4', 'Column5']
index_names = ['Row1', 'Row2', 'Row3', 'Row4', 'Row5']
custom_df = pd.DataFrame(np.random.rand(5, 5), columns=column_names, index=index_names)
custom_df

Column1   Column2   Column3   Column4   Column5
Row1  0.192615  0.266701  0.175553  0.111918  0.077534
Row2  0.642276  0.921164  0.261224  0.261387  0.326913
Row3  0.178570  0.779417  0.795028  0.545090  0.693560
Row4  0.518796  0.878645  0.958067  0.626891  0.128739
Row5  0.557365  0.374397  0.822782  0.216677  0.963333

In [17]:
print('Custom_df Separated into its individual Index: ', '\n')
print('Index: ', custom_df.index)
print('\nCustom_df Separated into its Values: ', '\n', '\nValues : ', custom_df.values)
print('\nCustom_df Separated into its Columns: ', '\n', '\nColumns : ', custom_df.columns)

Custom_df Separated into its individual Index:  

Index:  Index(['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], dtype='object')

Custom_df Separated into its Values:  
 
Values :  [[0.19261485 0.26670065 0.17555267 0.11191791 0.07753435]
 [0.64227594 0.92116415 0.26122386 0.26138746 0.32691317]
 [0.1785702  0.77941731 0.79502849 0.54509024 0.69356031]
 [0.51879576 0.87864484 0.95806692 0.62689071 0.12873863]
 [0.55736465 0.37439652 0.8227817  0.216677   0.96333264]]

Custom_df Separated into its Columns:  
 
Columns :  Index(['Column1', 'Column2', 'Column3', 'Column4', 'Column5'], dtype='object')
